# Generated by Django 4.2.6 on 2024-02-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='user',
            new_name='name',
        ),
    ]
