# Generated by Django 4.2.6 on 2024-02-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profil_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='name',
            new_name='user',
        ),
    ]
