# Generated by Django 4.2.6 on 2024-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
