# Generated by Django 4.2.6 on 2024-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profil_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profieImage',
            field=models.ImageField(default='profiles/user_default.png', upload_to='profiles/'),
        ),
    ]
