# Generated by Django 4.2.6 on 2024-02-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profil_profieimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='profieImage',
            new_name='profileImage',
        ),
    ]
