# Generated by Django 4.2.6 on 2024-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_profieimage_profil_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='xd',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
