# Generated by Django 4.2.6 on 2024-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profil_xd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='xd',
            new_name='dateBirth',
        ),
        migrations.AddField(
            model_name='profil',
            name='sexUser',
            field=models.CharField(choices=[('Male', 'Mężczyzna'), ('Female', 'Kobieta')], default='Female'),
        ),
    ]
