# Generated by Django 4.2.6 on 2024-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_xd_profil_datebirth_profil_sexuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
