# Generated by Django 4.2.6 on 2023-10-24 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategories',
            fields=[
                ('categoryName', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubBookCategories',
            fields=[
                ('subCategoryName', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcategories')),
            ],
        ),
    ]
